ItemApp/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ItemApp.Data;
using ItemApp.Models;

namespace ItemApp.Controllers
{
    public class ImagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ImagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Images
        public async Task<IActionResult> Index()
        {
            return View(await _context.Image.ToListAsync());
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.ID == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Images/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ImageLocation,P21ItemID")] Image image)
        {
            if (ModelState.IsValid)
            {
                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(image);
        }

        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ImageLocation,P21ItemID")] Image image)
        {
            if (id != image.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(image);
        }

        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.ID == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "ItemMaster",  new { id = image.P21ItemID });
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.ID == id);
        }
    }
}

ItemApp/Controllers/ItemMasterController.cs
using ItemApp.Data;
using ItemApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ItemApp.Controllers
{
    public class ItemMasterController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ItemMasterController(ApplicationDbContext applicationDbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._webHostEnvironment = webHostEnvironment;
            _context = applicationDbContext;
        }

        public async Task<IActionResult> SearchItem(string searchString)
        {
            var items = from i in _context.P21Item
                        select i;

            if (!string.IsNullOrEmpty(searchString))
            {
                items = items
                    .Where(i => i.Description.Contains(searchString)
                    || i.ItemID.Contains(searchString)
                    || i.ExtendedDescription.Contains(searchString));
            }
            else
            {
                items = items
                    .Where(i => i.inv_mast_uid == 0);
            }
            return View(await items.ToListAsync());
        }

        public async Task<IActionResult> SearchBin(string searchString)
        {
            var items = from i in _context.P21Item
                        select i;

            if (!string.IsNullOrEmpty(searchString))
            {
                items = items
                    .Where(i => i.PrimaryBin.Contains(searchString));
            }
            else
            {
                items = items
                    .Where(i => i.inv_mast_uid == 0);
            }
            return View(await items.ToListAsync());
        }
        public IActionResult AddImage(int? P21ItemID)
        {
            if (P21ItemID == 0)
            {
                return RedirectToAction("SearchItem");
            }
            ViewBag.P21ItemID = P21ItemID;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddImage([Bind("ID,ImageFile,P21ItemID")] Image image)
        {
            if (ModelState.IsValid)
            {
                if (image.ImageFile == null)
                {
                    return RedirectToAction("Details", new { id = image.P21ItemID });
                }

                int numberOfImages = _context.P21Item
                 .Include(s => s.Images).Where(m => m.inv_mast_uid == image.P21ItemID).SelectMany(o => o.Images).Count();
                numberOfImages += numberOfImages;

                var p21item = _context.P21Item.Where(m => m.inv_mast_uid == image.P21ItemID).FirstOrDefault();
                var P21ItemName = p21item.inv_mast_uid.ToString();

                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string extension = Path.GetExtension(image.ImageFile.FileName);
                string filename = "";
                string pathFileName = "";

                if (numberOfImages == 0)
                {
                    pathFileName = Path.Combine(wwwRootPath + "/images", P21ItemName + extension);
                    filename = P21ItemName + extension;
                }
                else
                {
                    pathFileName = Path.Combine(wwwRootPath + "/images", P21ItemName + "_" + numberOfImages.ToString() + extension);
                    filename = P21ItemName + "_" + numberOfImages.ToString() + extension;
                }

                // save image
                //string filename = Path.GetFileNameWithoutExtension(image.ImageFile.FileName);
                image.ImageLocation = filename;
                
                //pathFileName = Path.Combine(wwwRootPath + "/images", filename);
                using (var fileStream = new FileStream(pathFileName, FileMode.Create))
                {
                    await image.ImageFile.CopyToAsync(fileStream);
                }

                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = image.P21ItemID });

            }
            return RedirectToAction("SearchItem");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var P21Items = await _context.P21Item
                 .Include(s => s.Images)
                 .AsNoTracking()
                 .FirstOrDefaultAsync(m => m.inv_mast_uid == id);

            if (P21Items == null)
            {
                return RedirectToAction("SearchItem");
            }

            return View(P21Items);
        }
    }
}

ItemApp/Controllers/P21ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ItemApp.Data;
using ItemApp.Models;

namespace ItemApp.Controllers
{
    public class P21ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public P21ItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: P21Item
        public async Task<IActionResult> Index()
        {
            return View(await _context.P21Item.ToListAsync());
        }

        // GET: P21Item/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var p21Item = await _context.P21Item
                 .Include(s => s.Images)
                .FirstOrDefaultAsync(m => m.inv_mast_uid == id);
            if (p21Item == null)
            {
                return NotFound();
            }

            return View(p21Item);
        }

        // GET: P21Item/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: P21Item/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,inv_mast_uid,ItemID,Description,ExtendedDescription,PrimaryBin")] P21Item p21Item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(p21Item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(p21Item);
        }

        // GET: P21Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var p21Item = await _context.P21Item.FindAsync(id);
            if (p21Item == null)
            {
                return NotFound();
            }
            return View(p21Item);
        }

        // POST: P21Item/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,inv_mast_uid,ItemID,Description,ExtendedDescription,PrimaryBin")] P21Item p21Item)
        {
            if (id != p21Item.inv_mast_uid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(p21Item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!P21ItemExists(p21Item.inv_mast_uid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(p21Item);
        }

        // GET: P21Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var p21Item = await _context.P21Item
                .FirstOrDefaultAsync(m => m.inv_mast_uid == id);
            if (p21Item == null)
            {
                return NotFound();
            }

            return View(p21Item);
        }

        // POST: P21Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var p21Item = await _context.P21Item.FindAsync(id);
            _context.P21Item.Remove(p21Item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool P21ItemExists(int id)
        {
            return _context.P21Item.Any(e => e.inv_mast_uid == id);
        }
    }
}

ItemApp/Views/ItemMaster/AddImage.cshtml
@model ItemApp.Models.Image

@{
    ViewData["Title"] = "AddImage";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddImage" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" capture />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>

            <input hidden asp-for="P21ItemID" value="@ViewBag.P21ItemID" />

            <div class="form-group">
                <input type="submit" value="Add Image" class="btn btn-primary" />
                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@ViewBag.P21ItemID">Back to Detail</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ItemApp/Views/ItemMaster/Details.cshtml
@model ItemApp.Models.P21Item

@{
    ViewData["Title"] = "Details";
}




<div>
    <hr />
    <div class="card">
        <div class="card-header">
            <p>
                <span>@Html.DisplayFor(model => model.ItemID)</span><span> ( @Html.DisplayFor(model => model.inv_mast_uid) ) </span>
                <span style="float:right">
                    <a asp-action="AddImage" asp-route-P21ItemID="@Model.inv_mast_uid"><i style="font-size:larger" class="bi bi-card-image"></i></a>
                </span>
            </p>
        </div>
        <div class="card-body">
            <h5 class="card-title">@Html.DisplayFor(model => model.Description)</h5>
            
            <ul class="list-group list-group-flush">
                @foreach (var item in Model.Images)
                {
                    <li class="list-group-item">
                        <img class="img-fluid" src="~/images/@item.ImageLocation" asp-append-version="true" />
                        <a asp-action="Delete" asp-controller="Images" asp-route-id="@item.ID" class="btn btn-outline-danger">Delete</a>
                    </li>
                }
            </ul>
        </div>
        <div class="card-footer">
            @Html.DisplayFor(model => model.PrimaryBin)
        </div>
<div>
    <p><a asp-controller="P21Item" asp-action="Details" asp-route-id="@Model.inv_mast_uid">P21</a></p>
</div>
    </div>
</div>

ItemApp/Views/ItemMaster/SearchBin.cshtml
@model IEnumerable<ItemApp.Models.P21Item>

@{
    ViewData["Title"] = "SearchBin";
}

<div class="row">
    <div class="col-md-10">
        <form asp-action="SearchBin" asp-controller="ItemMaster">
            <p>
                <input type="text" name="searchString" autofocus placeholder="Bin Search" />
                <input type="submit" value="Search" />
            </p>
        </form>
    </div>
</div>

@foreach (var item in Model)
{
    <div class="card">
        <div class="card-header">
            <span><a asp-action="Details" asp-route-id="@item.inv_mast_uid">@Html.DisplayFor(modelItem => item.ItemID)</a></span>
            <span style="float:right">
                <a asp-action="AddImage" asp-route-P21ItemID="@item.inv_mast_uid"><i style="font-size:larger" class="bi bi-card-image"></i></a>
            </span>
        </div>
        <div class="card-body">
            <p>@Html.DisplayFor(modelItem => item.Description)</p>
            <p>@Html.DisplayFor(modelItem => item.ExtendedDescription)</p>
        </div>
        <div class="card-footer">
            <span>@Html.DisplayFor(modelItem => item.PrimaryBin)</span>
        </div>
    </div>
}

ItemApp/Views/ItemMaster/SearchItem.cshtml
@model IEnumerable<ItemApp.Models.P21Item>

@{
    ViewData["Title"] = "SearchItem";
}

<div class="row">
    <div class="col-md-10">
        <form asp-action="SearchItem" asp-controller="ItemMaster">
            <p>
                <input type="text" name="searchString" autofocus placeholder="Item Search" />
                <input type="submit" value="Search" />
            </p>
        </form>
    </div>
</div>

@foreach (var item in Model)
{
<div class="card">
    <div class="card-header">
        <span><a asp-action="Details" asp-route-id="@item.inv_mast_uid">@Html.DisplayFor(modelItem => item.ItemID)</a></span>
        <span style="float:right">
            <a asp-action="AddImage" asp-route-P21ItemID="@item.inv_mast_uid"><i style="font-size:larger" class="bi bi-card-image"></i></a>
        </span>
    </div>
    <div class="card-body">
        <p>@Html.DisplayFor(modelItem => item.Description)</p>
        <p>@Html.DisplayFor(modelItem => item.ExtendedDescription)</p>
    </div>
    <div class="card-footer">
        <span>@Html.DisplayFor(modelItem => item.PrimaryBin)</span>
    </div>
</div>
}