ItemApp/Models/P21Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ItemApp.Models
{
    public class P21Item
    {
        [Key]
        public int inv_mast_uid { get; set; }
        public string ItemID { get; set; }
        public string Description { get; set; }
        public string ExtendedDescription { get; set; }
        public string PrimaryBin { get; set; }
        public List<Image> Images { get; set; }
    }
}

ItemApp/Controllers/ItemMasterController.cs
using ItemApp.Data;
using ItemApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ItemApp.Controllers
{
    public class ItemMasterController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ItemMasterController(ApplicationDbContext applicationDbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._webHostEnvironment = webHostEnvironment;
            _context = applicationDbContext;
        }

        public async Task<IActionResult> SearchItem(string searchString)
        {
            var items = from i in _context.P21Item
                        select i;

            if (!string.IsNullOrEmpty(searchString))
            {
                items = items
                    .Where(i => i.Description.Contains(searchString)
                    || i.ItemID.Contains(searchString)
                    || i.ExtendedDescription.Contains(searchString));
            }
            else
            {
                items = items
                    .Where(i => i.inv_mast_uid == 0);
            }
            return View(await items.ToListAsync());
        }

        public async Task<IActionResult> SearchBin(string searchString)
        {
            var items = from i in _context.P21Item
                        select i;

            if (!string.IsNullOrEmpty(searchString))
            {
                items = items
                    .Where(i => i.PrimaryBin.Contains(searchString));
            }
            else
            {
                items = items
                    .Where(i => i.inv_mast_uid == 0);
            }
            return View(await items.ToListAsync());
        }
        public IActionResult AddImage(int? P21ItemID)
        {
            if (P21ItemID == 0)
            {
                return RedirectToAction("SearchItem");
            }
            ViewBag.P21ItemID = P21ItemID;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddImage([Bind("ID,ImageFile,P21ItemID")] Image image)
        {
            if (ModelState.IsValid)
            {
                if (image.ImageFile == null)
                {
                    return RedirectToAction("Details", new { id = image.P21ItemID });
                }

                int numberOfImages = _context.P21Item
                 .Include(s => s.Images).Where(m => m.inv_mast_uid == image.P21ItemID).SelectMany(o => o.Images).Count();
                numberOfImages += numberOfImages;

                var p21item = _context.P21Item.Where(m => m.inv_mast_uid == image.P21ItemID).FirstOrDefault();
                var P21ItemName = p21item.inv_mast_uid.ToString();

                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string extension = Path.GetExtension(image.ImageFile.FileName);
                string filename = "";
                string pathFileName = "";

                if (numberOfImages == 0)
                {
                    pathFileName = Path.Combine(wwwRootPath + "/images", P21ItemName + extension);
                    filename = P21ItemName + extension;
                }
                else
                {
                    pathFileName = Path.Combine(wwwRootPath + "/images", P21ItemName + "_" + numberOfImages.ToString() + extension);
                    filename = P21ItemName + "_" + numberOfImages.ToString() + extension;
                }

                // save image
                //string filename = Path.GetFileNameWithoutExtension(image.ImageFile.FileName);
                image.ImageLocation = filename;
                
                //pathFileName = Path.Combine(wwwRootPath + "/images", filename);
                using (var fileStream = new FileStream(pathFileName, FileMode.Create))
                {
                    await image.ImageFile.CopyToAsync(fileStream);
                }

                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = image.P21ItemID });

            }
            return RedirectToAction("SearchItem");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var P21Items = await _context.P21Item
                 .Include(s => s.Images)
                 .AsNoTracking()
                 .FirstOrDefaultAsync(m => m.inv_mast_uid == id);

            if (P21Items == null)
            {
                return RedirectToAction("SearchItem");
            }

            return View(P21Items);
        }
    }
}

ItemApp/Controllers/P21ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ItemApp.Data;
using ItemApp.Models;

namespace ItemApp.Controllers
{
    public class P21ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public P21ItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: P21Item
        public async Task<IActionResult> Index()
        {
            return View(await _context.P21Item.ToListAsync());
        }

        // GET: P21Item/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var p21Item = await _context.P21Item
                 .Include(s => s.Images)
                .FirstOrDefaultAsync(m => m.inv_mast_uid == id);
            if (p21Item == null)
            {
                return NotFound();
            }

            return View(p21Item);
        }

        // GET: P21Item/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: P21Item/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,inv_mast_uid,ItemID,Description,ExtendedDescription,PrimaryBin")] P21Item p21Item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(p21Item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(p21Item);
        }

        // GET: P21Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var p21Item = await _context.P21Item.FindAsync(id);
            if (p21Item == null)
            {
                return NotFound();
            }
            return View(p21Item);
        }

        // POST: P21Item/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,inv_mast_uid,ItemID,Description,ExtendedDescription,PrimaryBin")] P21Item p21Item)
        {
            if (id != p21Item.inv_mast_uid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(p21Item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!P21ItemExists(p21Item.inv_mast_uid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(p21Item);
        }

        // GET: P21Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var p21Item = await _context.P21Item
                .FirstOrDefaultAsync(m => m.inv_mast_uid == id);
            if (p21Item == null)
            {
                return NotFound();
            }

            return View(p21Item);
        }

        // POST: P21Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var p21Item = await _context.P21Item.FindAsync(id);
            _context.P21Item.Remove(p21Item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool P21ItemExists(int id)
        {
            return _context.P21Item.Any(e => e.inv_mast_uid == id);
        }
    }
}

ItemApp/Views/P21Item/Create.cshtml
@model ItemApp.Models.P21Item

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>P21Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="inv_mast_uid" class="control-label"></label>
                <input asp-for="inv_mast_uid" class="form-control" />
                <span asp-validation-for="inv_mast_uid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemID" class="control-label"></label>
                <input asp-for="ItemID" class="form-control" />
                <span asp-validation-for="ItemID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExtendedDescription" class="control-label"></label>
                <input asp-for="ExtendedDescription" class="form-control" />
                <span asp-validation-for="ExtendedDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryBin" class="control-label"></label>
                <input asp-for="PrimaryBin" class="form-control" />
                <span asp-validation-for="PrimaryBin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ItemApp/Views/P21Item/Delete.cshtml
@model ItemApp.Models.P21Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>P21Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.inv_mast_uid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.inv_mast_uid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExtendedDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExtendedDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryBin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryBin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="inv_mast_uid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ItemApp/Views/P21Item/Details.cshtml
@model ItemApp.Models.P21Item

@{
    Layout = null;
    ViewData["Title"] = "Details";
}

<div>
    <div class="card">
        <div class="card-body">
            @foreach (var item in Model.Images)
            {
                <img class="img-fluid" src="~/images/@item.ImageLocation" asp-append-version="true" />
            }
        </div>

    </div>
    <p><a asp-controller="ItemMaster" asp-action="Details" asp-route-id="@Model.inv_mast_uid">Item</a></p>
    </div>

ItemApp/Views/P21Item/Edit.cshtml
@model ItemApp.Models.P21Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>P21Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="inv_mast_uid" />
            <div class="form-group">
                <label asp-for="inv_mast_uid" class="control-label"></label>
                <input asp-for="inv_mast_uid" class="form-control" />
                <span asp-validation-for="inv_mast_uid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemID" class="control-label"></label>
                <input asp-for="ItemID" class="form-control" />
                <span asp-validation-for="ItemID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExtendedDescription" class="control-label"></label>
                <input asp-for="ExtendedDescription" class="form-control" />
                <span asp-validation-for="ExtendedDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryBin" class="control-label"></label>
                <input asp-for="PrimaryBin" class="form-control" />
                <span asp-validation-for="PrimaryBin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ItemApp/Views/P21Item/Index.cshtml
@model IEnumerable<ItemApp.Models.P21Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.inv_mast_uid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExtendedDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimaryBin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.inv_mast_uid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExtendedDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrimaryBin)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.inv_mast_uid">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.inv_mast_uid">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.inv_mast_uid">Delete</a>
                </td>
            </tr>
            <span><a asp-controller="ItemMaster" asp-action="Details" asp-route-id="@item.inv_mast_uid">Item</a></span>        }
    </tbody>
</table>